"use client";

import { useEffect, useState, type FormEvent } from "react";
import Markdown from "react-markdown";
import { getHealth, sendChat, type Agent, type ChatResponse, type Health } from "../lib/api";

const example = "Write a Python function to reverse a string.";
const specialists = [
  { id: "coding", mark: "</>", name: "Coding", description: "Build, explain & debug", ready: true },
  { id: "document", mark: "▤", name: "Documents", description: "PDF answers with citations", ready: false },
  { id: "search", mark: "⌕", name: "Search", description: "Find answers on the web", ready: false },
  { id: "research", mark: "◇", name: "Research", description: "Connect sources & ideas", ready: false },
] as const;

export default function Workspace() {
  const [health, setHealth] = useState<Health | null>(null);
  const [connection, setConnection] = useState("Connecting");
  const [message, setMessage] = useState(example);
  const [agent, setAgent] = useState<Agent>("auto");
  const [token, setToken] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [result, setResult] = useState<ChatResponse | null>(null);
  const [submitted, setSubmitted] = useState("");

  async function checkConnection() {
    setConnection("Connecting");
    try { setHealth(await getHealth()); setConnection("API connected"); }
    catch { setHealth(null); setConnection("API offline"); }
  }
  useEffect(() => { void checkConnection(); }, []);

  async function run(event?: FormEvent) {
    event?.preventDefault();
    if (busy || !message.trim()) return;
    setBusy(true); setError(""); setResult(null); setSubmitted(message.trim());
    try { setResult(await sendChat(message.trim(), agent, token)); }
    catch (failure) { setError(failure instanceof Error ? failure.message : "Something went wrong. Please try again."); }
    finally { setBusy(false); }
  }

  const provider = result?.provider ?? health?.provider;
  const searchEnabled = Boolean(health?.capabilities.search);
  const searchResult = result?.agent === "search";
  const providerNote = searchResult
    ? { title: "Search agent · Tavily sources", detail: "This answer is based on retrieved web results. Listed links are the returned URLs." }
    : provider === "bedrock"
      ? result?.provider === "bedrock"
        ? { title: "Bedrock response received", detail: "This response was generated by the configured Bedrock model." }
        : { title: "Bedrock configured · access not yet verified", detail: "Run a task to verify model access." }
      : provider === "demo"
        ? { title: "Demo mode · fixed sample response", detail: "This checks the full workflow with a fixed coding fixture. No AI model is called." }
        : { title: "Provider not yet verified", detail: "Connect the backend to confirm whether this workspace uses a model or the demo fixture." };

  return (
    <div className="workspace">
      <aside className="sidebar">
        <a className="brand" href="/" aria-label="NexusAI home"><span className="brand-icon">N</span>Nexus<span>AI</span></a>
        <div className="workspace-label">YOUR WORKSPACE <span>01</span></div>
        <button className={`nav-item ${agent === "auto" ? "selected" : ""}`} onClick={() => setAgent("auto")} disabled={busy}><span>✧</span> All agents <span className="small-arrow">↗</span></button>
        <p className="sidebar-heading">SPECIALISTS</p>
        <nav aria-label="Specialist agents">
          {specialists.map((item) => {
            const ready = item.id === "coding" || (item.id === "search" && Boolean(health?.capabilities.search));
            return (
            <button key={item.id} className={`specialist ${agent === item.id ? "active" : ""}`} disabled={!ready || busy} onClick={() => setAgent(item.id)}>
              <span className="agent-mark">{item.mark}</span><span className="specialist-text"><strong>{item.name}</strong><small>{item.description}</small></span>
              {!ready && <span className="planned">Soon</span>}
            </button>
            );
          })}
        </nav>
        <div className="sidebar-bottom"><span className="milestone">MILESTONE 01</span><h3>Start small.<br />Build something real.</h3><p>{health?.capabilities.search ? "Coding and Search are ready. Documents and Research are on the roadmap." : "Coding is ready. Three more specialists are on the roadmap."}</p><div className={`progress-track${health?.capabilities.search ? " two" : ""}`}><span /></div><small>{health?.capabilities.search ? "2 of 4 agents implemented" : "1 of 4 agents implemented"}</small></div>
        <div className="team"><span className="avatar">NX</span><div><strong>NexusAI team</strong><small>Hackathon workspace</small></div><span>↗</span></div>
      </aside>

      <main>
        <header className="topbar"><span>Workspace <span className="crumb">/</span> <strong>New task</strong></span><button className={`connection ${health ? "online" : ""}`} onClick={() => void checkConnection()} title="Check API connection"><i />{connection}<span>↻</span></button></header>
        <div className="content">
          <div className="intro"><div className="eyebrow"><span /> A LITTLE SPECIALIST KNOWLEDGE. A LOT OF POSSIBILITY.</div><h1>Big ideas.<br /><span>The right agent.</span></h1><p>Bring a task. Nexus routes it to a specialist<br className="desktop-break" /> and shows you how the work gets done.</p></div>

          <div className={`provider-note ${searchResult || provider === "bedrock" ? "bedrock" : ""}`} role="status"><span>{searchResult || provider === "bedrock" ? "✧" : "ⓘ"}</span><div><strong>{providerNote.title}</strong><p>{providerNote.detail}</p></div></div>

          <div className="working-grid">
            <section className="task-area" aria-labelledby="task-heading">
              <form className="composer" onSubmit={(event) => void run(event)}>
                <div className="card-heading"><h2 id="task-heading">What are we working on?</h2><span className="task-number">01 / NEW TASK</span></div>
                <label className="sr-only" htmlFor="message">Your task</label>
                <textarea id="message" value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Describe your coding task…" maxLength={12000} disabled={busy} required />
                <div className="composer-bottom"><label className="agent-select"><span>✧</span><select aria-label="Agent routing" value={agent} onChange={(event) => setAgent(event.target.value as Agent)} disabled={busy}><option value="auto">Auto-route</option><option value="coding">Coding agent</option>{searchEnabled && <option value="search">Search agent</option>}</select></label><button className="run-button" disabled={busy || !message.trim()} type="submit">{busy ? "Working…" : "Run task"}<span>{busy ? "◌" : "↗"}</span></button></div>
              </form>
              <div className="try-row"><span>TRY THIS</span><button disabled={busy} onClick={() => setMessage(example)}>Reverse a string <span>↗</span></button>{searchEnabled && <button disabled={busy} onClick={() => setMessage("What are the latest developments in AI agents?")}>Latest AI agents <span>↗</span></button>}{provider === "bedrock" && <button disabled={busy} onClick={() => setMessage("Explain Python list comprehensions with a simple example.")}>Explain some code <span>↗</span></button>}</div>
              <details className="access-settings"><summary>Workspace access token</summary><label htmlFor="token">For a protected demo API</label><input id="token" type="password" autoComplete="off" value={token} onChange={(event) => setToken(event.target.value)} placeholder="Enter the demo access token" /><small>Kept in this tab’s memory. Ask your team lead for the token.</small></details>

              {busy && <div className="loading-box" role="status"><span className="spinner" /><div><strong>Your task is running</strong><p>The completed activity trace will appear with the response.</p></div></div>}
              {error && <div className="error-box" role="alert"><strong>We couldn’t complete this task</strong><p>{error}</p><button onClick={() => void run()}>Try again ↗</button></div>}
              {result && <article className="result-card"><div className="result-header"><span className="result-agent">{result.agent === "search" ? "⌕" : "</>"} {result.agent} agent</span><span className="complete">✓ Complete</span></div><p className="submitted">{submitted}</p><div className="markdown"><Markdown skipHtml components={{ a: ({ children, ...props }) => <a {...props} target="_blank" rel="noopener noreferrer">{children}</a> }}>{result.answer}</Markdown></div>{result.citations.length > 0 && <ul className="citations">{result.citations.filter((item) => item.url).map((item) => <li key={item.url}><a href={item.url} target="_blank" rel="noopener noreferrer">{item.title || item.url}</a></li>)}</ul>}<div className="result-footer">{result.agent === "search" ? "Retrieved with Tavily" : result.provider === "demo" ? "Fixed demo fixture" : "Generated with Amazon Bedrock"}<span>Request {result.request_id.slice(0, 8)}</span></div></article>}
            </section>

            <aside className="activity-panel" aria-labelledby="activity-heading"><div className="activity-title"><h2 id="activity-heading">Agent activity</h2><span className="activity-count">{result ? result.activity.length : "—"}</span></div><p className="activity-subtitle">A clear view of the work.</p>{result ? <ol className="trace">{result.activity.map((item, index) => <li key={`${item.step}-${index}`}><span className="trace-check">✓</span><div><strong>{item.step.replaceAll("_", " ")}</strong><p>{item.detail}</p><small>{item.duration_ms.toLocaleString()} ms · completed</small></div></li>)}</ol> : <div className="activity-empty"><div className="orbit"><span>✧</span></div><strong>{busy ? "Task in progress" : "Ready when you are"}</strong><p>{busy ? "Waiting for the backend. Steps appear after the request completes." : "Run a task to see the selected agent, its steps, and the result."}</p></div>}<div className="trace-note"><span>◎</span> Completed steps from the API.<br />No simulated live activity.</div></aside>
          </div>
          <footer className="page-footer"><span>NEXUSAI / BUILT TO WORK TOGETHER</span><span>One workspace. Specialized intelligence.</span></footer>
        </div>
      </main>
    </div>
  );
}
